<?php
/*
 * (C) 2016 ${USER_NAME}
 */

namespace CornyPhoenix\Component\Redmine\Normalizer;


use Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter;

class NameConverter extends CamelCaseToSnakeCaseNameConverter
{

    public function denormalize($propertyName)
    {
        if ('is_' === substr($propertyName, 0, 3)) {
            $propertyName = substr($propertyName, 3);
        }

        $propertyName = parent::denormalize($propertyName); // TODO: Change the autogenerated stub

        return $propertyName;
    }
}